<!-- badges: start -->
<!-- badges: end -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  collapse = TRUE,
  comment = "#>"
)

library(globe4r)
library(htmltools)
```

```{r, echo=FALSE}
br()

div(
  class = "row",
  div(
    class = "col-md-4",
    img(
      src = "logo.png",
      class = "img-responsive responsive-img"
    )
  ),
  div(
    class = "col-md-8",
    p(
      "Interactive globes for R via",
      tags$a(
        "globe.gl", 
        href = "https://github.com/vasturiano/globe.gl", 
        target = "_blank"
      ),
      "Create 3D globes with points, bar, choropleth (polygons), arcs, and labels."
    ),
    p(
      tags$a(
        tags$i(class = "fa fa-rocket"),
        "Get Started",
        class = "btn btn-primary",
        href = "articles/get-started.html"
      ),
      tags$a(
        tags$i(class = "fa fa-desktop"),
        "Shiny",
        class = "btn btn-default",
        href = "articles/shiny.html"
      )
    )
  )
)
br()
```

## Installation

You can install the globe4r from Github:

```r
# install.packages("remotes")
remotes::install_github("JohnCoene/globe4r")
```

## Examples

```{r, echo = FALSE}
div(
  class = "row",
  div(class = "col-md-3",
    tags$a(
      "Bars",
      class = "btn btn-default",
      href = "bars.html",
      target = "_blank",
      style = "width:100%;"
    )
  ),
  div(class = "col-md-3",
    tags$a(
      "Acs",
      class = "btn btn-default",
      href = "arcs.html",
      target = "_blank",
      style = "width:100%;"
    )
  ),
  div(class = "col-md-3",
    tags$a(
      "Labels",
      class = "btn btn-default",
      href = "labels.html",
      target = "_blank",
      style = "width:100%;"
    )
  ),
  div(class = "col-md-3",
    tags$a(
      "Polygons",
      class = "btn btn-default",
      href = "choropleth.html",
      target = "_blank",
      style = "width:100%;"
    )
  )
)
```
