#' Points
#' 
#' Add points to a globe.
#' 
#' @inheritParams globe_points
#' @param text Bare column name containing text to display on globe.
#' @param size Bare column name of or the label text height, in angular degrees.
#' @param rotation Bare column name for the label rotation in degrees. 
#' The rotation is performed clockwise along the axis of its latitude parallel plane.
#' @param include_dot Bare column name for for whether to include a dot marker next 
#' to the text indicating the exact \code{lat}, \code{lon} coordinates of the label. 
#' If enabled the text will be rendered offset from the dot.
#' @param dot_radius Bare column name for the radius of the dot marker, in angular degrees.
#' @param dot_orientation Bare column name for the orientation of the label if the 
#' dot marker is present. Possible values are right, top and bottom.
#' @param type_face Typeface to use for labels. Supports any typeface font 
#' generated by \href{http://gero3.github.io/facetype.js/}{Facetype.js}.
#' 
#' @examples
#' create_globe() %>% 
#'   globe_img_url() %>% 
#'   globe_labels(
#'     quakes,
#'     lat,
#'     long,
#'     text = stations
#'   )
#' 
#' library(shiny)
#' 
#' ui <- fluidPage(
#'   actionButton("add", "add quakes labels"),
#'   globeOutput("globe")
#' )
#' 
#' server <- function(input, output){
#'   output$globe <- renderGlobe({
#'     create_globe() %>% 
#'       globe_img_url() 
#'   })
#' 
#'   observeEvent(input$add, {
#'     globeProxy("globe") %>% 
#'       globe_labels(
#'         quakes,
#'         lat,
#'         long,
#'         text = stations
#'       )
#'   })
#' }
#' 
#' \dontrun{shinyApp(ui, server)}
#' 
#' @export
globe_labels <- function(globe, data, lat = NULL, lon = NULL, color = NULL, 
  text = NULL, label = NULL, altitude = NULL, size = NULL, rotation = NULL, 
  include_dot = NULL, dot_radius = NULL, dot_orientation = NULL, resolution = 2L, 
  type_face = NULL, transition = 1000L, on_click = NULL, on_right_click = NULL, 
  on_hover = NULL) UseMethod("globe_labels")

#' @export
#' @method globe_labels globe
globe_labels.globe <- function(globe, data, lat = NULL, lon = NULL, color = NULL, 
  text = NULL, label = NULL, altitude = NULL, size = NULL, rotation = NULL, 
  include_dot = NULL, dot_radius = NULL, dot_orientation = NULL, resolution = 2L, 
  type_face = NULL, transition = 1000L, on_click = NULL, on_right_click = NULL, 
  on_hover = NULL){

  # check inputs
  assert_that(not_missing(data))

  # enquo all things
  lat_enquo <- rlang::enquo(lat)
  lon_enquo <- rlang::enquo(lon)
  text_enquo <- rlang::enquo(text)
  label_enquo <- rlang::enquo(label)
  color_enquo <- rlang::enquo(color)
  altitude_enquo <- rlang::enquo(altitude)
  size_enquo <- rlang::enquo(size)
  rotation_enquo <- rlang::enquo(rotation)
  include_dot_enquo <- rlang::enquo(include_dot)
  dot_radius_enquo <- rlang::enquo(dot_radius)
  dot_orientation_enquo <- rlang::enquo(dot_orientation)

  # create points array
  globe$x$labelsData <- data %>% 
    select(
      lat = !!lat_enquo,
      lng = !!lon_enquo,
      text = !!text_enquo,
      label = !!label_enquo,
      color = !!color_enquo,
      altitude = !!altitude_enquo,
      size = !!size_enquo,
      rotation = !!rotation_enquo,
      include_dot = !!include_dot_enquo,
      dot_radius = !!dot_radius_enquo,
      dot_orientation = !!dot_orientation_enquo
    )

  # force character conversion or it's not drawn
  if("text" %in% names(globe$x$labelsData))
    globe$x$labelsData$text <- as.character(globe$x$labelsData$text)
  
  globe$x$labelColor <- if(!rlang::quo_is_null(color_enquo)) "color"
  globe$x$labelAltitude <- if(!rlang::quo_is_null(altitude_enquo)) "altitude"
  globe$x$labelSize <- if(!rlang::quo_is_null(size_enquo)) "size"
  globe$x$labelText <- if(!rlang::quo_is_null(text_enquo)) "text"
  globe$x$labelLabel <- if(!rlang::quo_is_null(label_enquo)) "label"
  globe$x$labelRotation <- if(!rlang::quo_is_null(rotation_enquo)) "rotation"
  globe$x$labelIncludeDot <- if(!rlang::quo_is_null(include_dot_enquo)) "include_dot"
  globe$x$labelDotRadius <- if(!rlang::quo_is_null(dot_radius_enquo)) "dot_radius"
  globe$x$labelDotOrientation <- if(!rlang::quo_is_null(dot_orientation_enquo)) "dot_orientation"
  globe$x$labelResolution <- resolution
  globe$x$labelTypeFace <- type_face
  globe$x$labelTransitionDuration <- transition
  globe$x$onLabelClick <- if(!is.null(on_click)) htmlwidgets::JS(on_click)
  globe$x$onLabelRightClick <- if(!is.null(on_right_click)) htmlwidgets::JS(on_right_click)
  globe$x$onLabelHover <- if(!is.null(on_hover)) htmlwidgets::JS(on_hover)

  return(globe)
}

#' @export
#' @method globe_labels globeProxy
globe_labels.globeProxy <- function(globe, data, lat = NULL, lon = NULL, color = NULL, 
  text = NULL, label = NULL, altitude = NULL, size = NULL, rotation = NULL, 
  include_dot = NULL, dot_radius = NULL, dot_orientation = NULL, resolution = 2L, 
  type_face = NULL, transition = 1000L, on_click = NULL, on_right_click = NULL, 
  on_hover = NULL){

  # check inputs
  assert_that(not_missing(data))

  # enquo all things
  lat_enquo <- rlang::enquo(lat)
  lon_enquo <- rlang::enquo(lon)
  text_enquo <- rlang::enquo(text)
  label_enquo <- rlang::enquo(label)
  color_enquo <- rlang::enquo(color)
  altitude_enquo <- rlang::enquo(altitude)
  size_enquo <- rlang::enquo(size)
  rotation_enquo <- rlang::enquo(rotation)
  include_dot_enquo <- rlang::enquo(include_dot)
  dot_radius_enquo <- rlang::enquo(dot_radius)
  dot_orientation_enquo <- rlang::enquo(dot_orientation)

  msg <- list(id = globe$id)

  # create points array
  msg$labelsData <- data %>% 
    select(
      lat = !!lat_enquo,
      lng = !!lon_enquo,
      text = !!text_enquo,
      label = !!label_enquo,
      color = !!color_enquo,
      altitude = !!altitude_enquo,
      size = !!size_enquo,
      rotation = !!rotation_enquo,
      include_dot = !!include_dot_enquo,
      dot_radius = !!dot_radius_enquo,
      dot_orientation = !!dot_orientation_enquo
    )

  # force character conversion or it's not drawn
  if("text" %in% names(msg$labelsData))
    msg$labelsData$text <- as.character(msg$labelsData$text)
  
  msg$labelsData <- apply(msg$labelsData, 1, as.list)
  
  msg$labelColor <- if(!rlang::quo_is_null(color_enquo)) "color"
  msg$labelAltitude <- if(!rlang::quo_is_null(altitude_enquo)) "altitude"
  msg$labelSize <- if(!rlang::quo_is_null(size_enquo)) "size"
  msg$labelText <- if(!rlang::quo_is_null(text_enquo)) "text"
  msg$labelLabel <- if(!rlang::quo_is_null(label_enquo)) "label"
  msg$labelRotation <- if(!rlang::quo_is_null(rotation_enquo)) "rotation"
  msg$labelIncludeDot <- if(!rlang::quo_is_null(include_dot_enquo)) "include_dot"
  msg$labelDotRadius <- if(!rlang::quo_is_null(dot_radius_enquo)) "dot_radius"
  msg$labelDotOrientation <- if(!rlang::quo_is_null(dot_orientation_enquo)) "dot_orientation"
  msg$labelResolution <- resolution
  msg$labelTypeFace <- type_face
  msg$labelTransitionDuration <- transition
  msg$onLabelClick <- if(!is.null(on_click)) htmlwidgets::JS(on_click)
  msg$onLabelRightClick <- if(!is.null(on_right_click)) htmlwidgets::JS(on_right_click)
  msg$onLabelHover <- if(!is.null(on_hover)) htmlwidgets::JS(on_hover)

  globe$session$sendCustomMessage("globe_labels", msg)

  return(globe)
}
